-- MySQL Script generated by MySQL Workbench
-- Wed Oct 18 14:50:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema registro_viaje
-- -----------------------------------------------------
-- El Viaje Amplia Tu Cultura Humana.

-- -----------------------------------------------------
-- Schema registro_viaje
--
-- El Viaje Amplia Tu Cultura Humana.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registro_viaje` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `registro_viaje` ;

-- -----------------------------------------------------
-- Table `registro_viaje`.`viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_viaje`.`viaje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Numero_Domicilio` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Codigo_Postal` VARCHAR(45) NOT NULL,
  `Presupuesto` VARCHAR(45) NOT NULL,
  `Numero_Personas` VARCHAR(45) NOT NULL,
  `Forma_Pago` VARCHAR(45) NOT NULL,
  `Pasaporte` VARCHAR(45) NOT NULL,
  `Inicio_Viaje` DATE NOT NULL,
  `Fin_Viaje` DATE NOT NULL,
  `Destino_Viaje` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
